import { Metadata } from "next";
import React from "react";

interface IProductPageProps {
  params: {
    projectId: string;
  };
}

export const metadata: Metadata = {
  title: "Design",
  description: "Generated by create next app",
};

const CategoryPage = (props: IProductPageProps) => {
  const { params } = props;
  const currentProject = params.projectId;

  return <h1>Projet : {currentProject}</h1>;
};

export default CategoryPage;
