import type { Metadata } from "next";
import { Almarai, Merienda } from "next/font/google";
import "./styles/index.scss";
import MainNav from "./components/main-nav";
import MainFooter from "./components/main-footer";

const almarai = Almarai({
  weight: ["400", "700"],
  subsets: ["arabic"],
  variable: "--font-family-base",
});

const merienda = Merienda({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-family-headings",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${almarai.className} ${merienda.className}`}>
        <MainNav />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
